name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # change if needed

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build
